const ProjectList = [
    {
        id: 1, 
        src: "./assets/img-ratethegords.png",
        altTag: "Rate The Gords", 
        title: "Rate The Gords", 
        details: "A place to rate Canada's iconic Gords", 
        specs: "CSS | Express | Javascript | MongoDB | Node.js | React.js", 
        url:"https://ratethegords.herokuapp.com/",
    },
    {
        id: 2, 
        src: "./assets/img-boq.png",
        altTag: "Bay of Quinte, Green Party of Ontario", 
        title: "Bay of Quinte, Green Party of Ontario", 
        details: "A custom wordpress theme for Bay of Quinte's Green Party of Ontario riding", 
        specs: "CSS | JavaScript | PHP | Wordpress ", 
        url:"https://bayofquintegpo.ca/",
    },
    {
        id: 3, 
        src: "./assets/img-cuecards.png",
        altTag: "CueCards: Online Study Tool", 
        title: "Cue Cards: Online Study Tool", 
        details: "A site to create your own cuecards on any topic and quiz yourself to test your knowledge", 
        specs: "CSS | Express | Javascript | MongoDB | Node.js | React.js" ,
        url:"https://cuecards-aw22.herokuapp.com/",
    },
    {
        id: 4, 
        src: "./assets/img-gmm.png",
        altTag: "Girl Meet Money: Blueprint Diagnostic Quiz", 
        title: "Girl Meet Money: Blueprint Diagnostic Quiz", 
        details: "A custom online quiz widget embedded to client shopify site", 
        specs: "CSS | HTML | JavaScript", 
        url:"https://girlmeetmoney.com/pages/gmm-diagnostic-quiz",
    },
    {
        id: 5, 
        src: "./assets/img-pkew.png",
        altTag: "PkewX3 Artist Promo Site", 
        title: "PkewX3", 
        details: "A custom musician promo site for PkewX3. Up to date show details via Bands in Town API integreation", 
        specs: "CSS | HTML | JavaScript | Bands in Town API | Swiper API", 
        url:"https://pkewx3.com/",
    },
    {
        id: 6, 
        src: "./assets/img-javascriptmugs.png",
        altTag: "JavaScript: Custom Mugs", 
        title: "JavaScript: Custom Mugs", 
        details: "A fullstack e-commerce store for user designed customized mugs", 
        specs: "CSS | Express | GraphQL | JavaScript | JWT | MongoDB | Node.js | React.js | Stripe", 
        url:"https://whispering-inlet-47426.herokuapp.com/",
    },
]

export default ProjectList;
